version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql-db
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      #MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    restart: 'no'
    links:
      - 'mysql:db'
    ports:
      - '9002:80'


volumes:
  db-data:

networks:
  mysqlStack:



